# Generated by Django 4.2.3 on 2023-07-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=10, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=30, null=True)),
                ('invoice_duedate', models.DateField(blank=True, null=True)),
                ('Product', models.CharField(blank=True, max_length=20, null=True)),
                ('Quantity', models.CharField(blank=True, max_length=20, null=True)),
                ('Rate', models.CharField(blank=True, max_length=50, null=True)),
                ('Total', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
